#!/usr/bin/env bash
#
# Installs the committed shared scheme (SchemeTemplates/NativeBrowser.xcscheme)
# into the generated Xcode project.
#
#   Scripts/sync_scheme.sh
#
# NativeBrowser.xcodeproj is generated by XcodeGen and is not committed, and
# XcodeGen's generated scheme has no TestAction - so the unit tests added in
# Milestone 2 would not be runnable. The scheme is therefore kept in
# SchemeTemplates/ and copied in after every generate. Run this after
# "xcodegen generate" (Scripts/build.sh does it automatically) and before
# "xcodebuild ... test".
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCHEME_NAME="NativeBrowser"
SOURCE="$REPO_ROOT/SchemeTemplates/$SCHEME_NAME.xcscheme"
DESTINATION_DIR="$REPO_ROOT/$SCHEME_NAME.xcodeproj/xcshareddata/xcschemes"
DESTINATION="$DESTINATION_DIR/$SCHEME_NAME.xcscheme"

if [ ! -f "$SOURCE" ]; then
  echo "error: $SOURCE is missing" >&2
  exit 1
fi
if [ ! -d "$REPO_ROOT/$SCHEME_NAME.xcodeproj" ]; then
  echo "error: $SCHEME_NAME.xcodeproj not found; run xcodegen generate first" >&2
  exit 1
fi

mkdir -p "$DESTINATION_DIR"
# The template's buildable BlueprintIdentifiers are target *names*, which is
# what XcodeGen uses for the project's blueprint identifiers.
cp "$SOURCE" "$DESTINATION"
echo "scheme: installed $SCHEME_NAME.xcscheme (shared, with TestAction)"
